import Head from "next/head";
import { Layout } from "~/components/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <h1>Cool blockchain app</h1>
        </main>
      </Layout>
    </>
  );
}
