import Head from "next/head";
import { Layout } from "~/components/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <div
            className="hero min-h-screen"
            style={{
              backgroundImage:
                "url(https://daisyui.com/images/stock/photo-1507358522600-9f71e620c44e.jpg)",
            }}
          >
            <div className="hero-overlay bg-opacity-60"></div>
            <div className="hero-content text-center">
              <div className="max-w-md">
                <h1 className="mb-5 text-5xl font-bold">Explore and Invest!</h1>
                <p className="mb-5">Lorem ipsum</p>
              </div>
            </div>
          </div>
        </main>
      </Layout>
    </>
  );
}
